schema_version: 20180708
name: ticket-manager-c
version: 2.0.0
runtime: java11
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.124
run_image: fnproject/fn-java-fdk:jre11-1.0.124
cmd: com.minsait.onesait.ManagerAEntrypoint::handleRequest
triggers:
- name: endpoint
  type: http
  source: /c/fire
